//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by w3xmaxtools.rc
//
#define IDI_DISK                        5
#define IDD_W3D_MAT_SURFACE_TYPE        9
#define IDD_W3D_MAT_PASS_COUNT          10
#define IDD_W3D_MAT_PASS_COUNT_POPUP    11
#define IDD_W3D_MAT_PASS                12
#define IDD_W3D_MAT_PASS_VERTEX         13
#define IDD_W3D_MAT_PASS_SHADER         14
#define IDD_W3D_MAT_PASS_TEXTURES       15
#define IDD_W3D_UTIL_EXPORT_SETTINGS    16
#define IDS_SURFACE_TYPE                103
#define IDS_MATERIAL_SURFACE_TYPE       104
#define IDS_MATERIAL_PASS_COUNT         105
#define IDS_PASS1                       106
#define IDS_STATIC_SORTING_LEVEL        107
#define IDS_ENABLED                     108
#define IDS_SURFACE_TYPE_LIGHT_METAL    109
#define IDS_SURFACE_TYPE_HEAVY_METAL    110
#define IDS_SURFACE_TYPE_WATER          111
#define IDS_SURFACE_TYPE_SAND           112
#define IDS_SURFACE_TYPE_DIRT           113
#define IDS_SURFACE_TYPE_MUD            114
#define IDS_SURFACE_TYPE_GRASS          115
#define IDS_PASS2                       116
#define IDS_SURFACE_TYPE_WOOD           117
#define IDS_SURFACE_TYPE_CONCRETE       118
#define IDS_SURFACE_TYPE_FLESH          119
#define IDS_SURFACE_TYPE_ROCK           120
#define IDS_SURFACE_TYPE_SNOW           121
#define IDS_SURFACE_TYPE_ICE            122
#define IDS_SURFACE_TYPE_DEFAULT        123
#define IDS_SURFACE_TYPE_GLASS          124
#define IDS_SURFACE_TYPE_CLOTH          125
#define IDS_SURFACE_TYPE_TIBERIUM_FIELD 126
#define IDS_SURFACE_TYPE_FOLIAGE_PERMEABLE 127
#define IDS_SURFACE_TYPE_GLASS_PERMEABLE 128
#define IDS_SURFACE_TYPE_ICE_PERMEABLE  129
#define IDS_SURFACE_TYPE_CLOTH_PERMEABLE 130
#define IDS_SURFACE_TYPE_ELECTRICAL     131
#define IDS_SURFACE_TYPE_ELECTRICAL_PERMEABLE 132
#define IDS_SURFACE_TYPE_FLAMMABLE      133
#define IDS_SURFACE_TYPE_FLAMMABLE_PERMEABLE 134
#define IDS_SURFACE_TYPE_STEAM          135
#define IDS_SURFACE_TYPE_STEAM_PERMEABLE 136
#define IDS_SURFACE_TYPE_WATER_PERMEABLE 137
#define IDS_SURFACE_TYPE_TIBERIUM_WATER 138
#define IDS_SURFACE_TYPE_TIBERIUM_WATER_PERMEABLE 139
#define IDS_SURFACE_TYPE_UNDERWATER_DIRT 140
#define IDS_SURFACE_TYPE_UNDERWATER_TIBERIUM_DIRT 141
#define IDS_PASS3                       142
#define IDS_PASS4                       143
#define IDS_AMBIENT_COLOUR              144
#define IDS_BLEND_WRITE_Z_BUFFER        145
#define IDS_STAGE_0_TEXTURE             146
#define IDS_STAGE_1_TEXTURE             147
#define IDS_DIFFUSE_COLOUR              148
#define IDS_SPECULAR_COLOUR             149
#define IDS_EMISSIVE_COLOUR             150
#define IDS_SPECULAR_TO_DIFFUSE         151
#define IDS_OPACITY                     152
#define IDS_TRANSLUCENCY                153
#define IDS_SHININESS                   154
#define IDS_STAGE_0_MAPPING             155
#define IDD_W3D_UTIL_TOOLS              155
#define IDS_STAGE_0_MAPPING_ARGS        156
#define IDS_STAGE_0_MAPPING_UV_CHANNEL  157
#define IDD_W3D_UTIL_NODE_NAMES         157
#define IDS_STAGE_1_MAPPING             158
#define IDD_W3D_UTIL_MTL_NAMES          158
#define IDS_STAGE_1_MAPPING_ARGS        159
#define IDD_W3D_UTIL_NAME_EXTENSION     159
#define IDS_STAGE_1_MAPPING_UV_CHANNEL  160
#define IDD_W3D_EXPORT                  160
#define IDS_BLEND_MODE                  161
#define IDD_W3D_EXPORT_HIERARCHICAL_MODEL 161
#define IDB_W3D_HUB_LOGO                161
#define IDS_BLEND_MODE_SRC              162
#define IDD_W3D_EXPORT_HIERARCHICAL_ANIMATED_MODEL 162
#define IDS_BLEND_MODE_DEST             163
#define IDD_W3D_EXPORT_ANIMATION        163
#define IDS_WRITE_Z_BUFFER              164
#define IDD_W3D_EXPORT_SKELETON         164
#define IDS_ALPHA_TEST                  165
#define IDD_W3D_EXPORT_TERRAIN          165
#define IDS_DEFAULTS                    166
#define IDD_W3D_EXPORT_SIMPLE_MESH      166
#define IDS_PRIMARY_GRADIENT            167
#define IDD_W3D_EXPORT_LOG              167
#define IDS_SECONDARY_GRADIENT          168
#define IDD_W3D_COMPRESSION             168
#define IDS_DEPTH_COMPARISON            169
#define IDS_DETAIL_COLOUR               170
#define IDS_DETAIL_ALPHA                171
#define IDS_PUBLISH                     172
#define IDS_DISPLAY                     173
#define IDS_CLAMP_U                     174
#define IDS_CLAMP_V                     175
#define IDS_NO_LOD                      176
#define IDS_ANIM_FRAMES                 177
#define IDS_ANIM_FPS                    178
#define IDS_ANIM_MODE                   179
#define IDS_PASS_HINT                   180
#define IDS_ALPHA_BITMAP                181
#define IDS_SURFACE_TYPE_BLUE_TIBERIUM  182
#define IDS_SURFACE_TYPE_RED_TIBERIUM   183
#define IDS_SURFACE_TYPE_TIBERIUM_VEINS 184
#define IDS_SURFACE_TYPE_LASER          185
#define IDS_SURFACE_TYPE_SNOW_PERMIABLE 186
#define IDS_SURFACE_TYPE_ELECTRICAL_GLASS 187
#define IDS_SURFACE_TYPE_ELECTRICAL_GLASS_PERMEABLE 188
#define IDS_SURFACE_TYPE_SLUSH          189
#define IDS_SURFACE_TYPE_EXTRA_1        190
#define IDS_SURFACE_TYPE_EXTRA_2        191
#define IDS_SURFACE_TYPE_EXTRA_3        192
#define IDS_SURFACE_TYPE_EXTRA_4        193
#define IDS_SURFACE_TYPE_EXTRA_5        194
#define IDS_SURFACE_TYPE_EXTRA_6        195
#define IDS_SURFACE_TYPE_EXTRA_7        196
#define IDS_SURFACE_TYPE_EXTRA_8        197
#define IDC_SURFACE_TYPE                1007
#define IDC_STATIC_SORT_ON              1008
#define IDC_STATIC_SORT_LVL_SPIN        1010
#define IDC_STATIC_SORT_LVL_EDIT        1011
#define IDC_PASS_COUNT_SPIN             1013
#define IDC_PASS_COUNT_SPIN_EDIT        1014
#define IDC_BTN_PASS_COUNT_CHANGE       1015
#define IDC_PASS_COUNT_DISPLAY_EDIT     1016
#define IDC_PASS_TABS                   1020
#define IDC_AMBIENT_COLOUR              1021
#define IDC_DIFFUSE_COLOUR              1022
#define IDC_SPECULAR_COLOUR             1023
#define IDC_EMISSIVE_COLOUR             1024
#define IDC_SPECULAR_TO_DIFFUSE         1025
#define IDC_OPACITY_EDIT                1026
#define IDC_OPACITY_SPIN                1027
#define IDC_TRANSLUCENCY_EDIT           1028
#define IDC_SELECTED_EDIT               1028
#define IDC_TRANSLUCENCY_SPIN           1029
#define IDC_SHININESS_EDIT              1030
#define IDC_SHININESS_SPIN              1031
#define IDC_STAGE_0_MAPPING_TYPE        1032
#define IDC_STAGE_0_MAPPING_ARGS        1033
#define IDC_STAGE_0_UV_CHAN_EDIT        1034
#define IDC_STAGE_0_UV_CHAN_SPIN        1035
#define IDC_STAGE_1_MAPPING_TYPE        1036
#define IDC_STAGE_1_MAPPING_ARGS        1037
#define IDC_STAGE_1_UV_CHAN_EDIT        1038
#define IDC_STAGE_1_UV_CHAN_SPIN        1039
#define IDC_STAGE_0_ENABLED             1040
#define IDC_STAGE_1_ENABLED             1041
#define IDC_CUSTOM_BLEND_MODE_SRC       1042
#define IDC_CUSTOM_BLEND_MODE_DEST      1043
#define IDC_BTN_BLEND_DEFAULTS          1044
#define IDC_SHADER_PRI_GRADIENT         1045
#define IDC_SHADER_SEC_GRADIENT         1046
#define IDC_SHADER_DEPTH_CMP            1047
#define IDC_SHADER_DETAIL_COLOUR        1048
#define IDC_SHADER_DETAIL_ALPHA         1049
#define IDC_BLEND_WRITE_ZBUFFER         1050
#define IDC_STAGE_0_TEXTURE_MAP         1052
#define IDC_STAGE_1_TEXTURE_MAP         1053
#define IDC_STAGE_0_CLAMP_U             1054
#define IDC_STAGE_0_CLAMP_V             1055
#define IDC_STAGE_0_NO_LOD              1056
#define IDC_STAGE_0_PUBLISH             1057
#define IDC_STAGE_0_DISPLAY             1058
#define IDC_STAGE_0_FRAMES_EDIT         1059
#define IDC_STAGE_0_FRAMES_SPIN         1060
#define IDC_STAGE_0_FPS_EDIT            1061
#define IDC_STAGE_0_FPS_SPIN            1062
#define IDC_STAGE_0_ANIM_MODE           1063
#define IDC_STAGE_0_PASS_HINT           1064
#define IDC_STAGE_0_ALPHA_BITMAP        1065
#define IDC_EXPORT_TRANSFORM            1065
#define IDC_STAGE_1_CLAMP_U             1066
#define IDC_EXPORT_GEOMETRY             1066
#define IDC_STAGE_1_CLAMP_V             1067
#define IDC_STAGE_1_NO_LOD              1068
#define IDC_STAGE_1_PUBLISH             1069
#define IDC_GEOM_NORMAL                 1069
#define IDC_STAGE_1_DISPLAY             1070
#define IDC_GEOM_CAM_PARAL              1070
#define IDC_STAGE_1_FRAMES_EDIT         1071
#define IDC_GEOM_CAM_ORIENT             1071
#define IDC_STAGE_1_FRAMES_SPIN         1072
#define IDC_GEOM_AABOX                  1072
#define IDC_STAGE_1_FPS_EDIT            1073
#define IDC_GEOM_OBBOX                  1073
#define IDC_STAGE_1_FPS_SPIN            1074
#define IDC_STAGE_1_ANIM_MODE           1075
#define IDC_STAGE_1_PASS_HINT           1076
#define IDC_STAGE_1_ALPHA_BITMAP        1077
#define IDC_TWO_SIDED                   1077
#define IDC_BLEND_ALPHA_TEST            1078
#define IDC_HIDE                        1078
#define IDC_BLEND_MODE                  1079
#define IDC_Z_NORMAL                    1079
#define IDC_KEEP_NORMAL                 1080
#define IDC_VALPHA                      1081
#define IDC_SHADOW                      1082
#define IDC_JOYPADPICK                  1083
#define IDC_STATIC_SORTING              1088
#define IDC_PHYSICAL                    1089
#define IDC_PROJECTILE                  1090
#define IDC_VIS                         1092
#define IDC_STATIC_SORT_LEVEL_EDIT      1094
#define IDC_STATIC_SORT_LEVEL_SPIN      1095
#define IDC_ASSIGN_MATERIAL_NAMES       1096
#define IDC_ASSIGN_EXTENSIONS           1097
#define IDC_ASSIGN_NODE_NAMES           1099
#define IDC_SELECT_GEOMETRY             1100
#define IDC_SELECT_BONES                1101
#define IDC_SELECT_ALPHA_MESHES         1102
#define IDC_SELECT_PHYS                 1103
#define IDC_SELECT_PROJ                 1104
#define IDC_SELECT_VIS                  1105
#define IDC_ROOT_NAME                   1107
#define IDC_ASSIGN_NAMES                1108
#define IDC_MAXROTATION                 1108
#define IDC_PREFIX                      1109
#define IDC_ASSIGN_PREFIX               1110
#define IDC_STARTING_INDEX_EDIT         1111
#define IDC_STARTING_INDEX_SPIN         1112
#define IDC_SUFFIX                      1113
#define IDC_ASSIGN_SUFFIX               1114
#define IDC_ASSIGN_COLLISION_FLAGS      1115
#define IDC_AFFECT_ALL                  1116
#define IDC_AFFECT_SELECTED             1117
#define IDC_EXTENSION_NUMBER_EDIT       1117
#define IDC_EXTENSION_NUMBER_SPIN       1118
#define IDC_SMOOTH_VERTICES             1124
#define IDC_OPT_COLLISONS               1125
#define IDC_USE_EXT_SKELETON            1127
#define IDC_BROWSE                      1128
#define IDC_FRAMES_EDIT                 1129
#define IDC_FRAMES_SPIN                 1130
#define IDC_FRAMES_TO_EDIT              1131
#define IDC_FRAMES_TO_SPIN              1132
#define IDC_REVIEW_LOG                  1134
#define IDC_HIERARCHICAL_MODEL          1135
#define IDC_HIERARCHICAL_ANIMATED_MODEL 1136
#define IDC_PURE_ANIMATION              1137
#define IDC_SKELETON                    1138
#define IDC_SIMPLE_MESH                 1140
#define IDC_SETTINGS_PANEL              1141
#define IDC_STATIC_SORT_LEVEL_LABEL     1145
#define IDC_COMPRESSIONSETTINGS         1151
#define IDC_TIMECODED                   1152
#define IDC_MAXTRANSLATION              1153
#define IDC_KEYREDUCTION                1154
#define IDC_FORCEKEYREDUCTION           1155
#define IDC_MAXVISIBILITY               1156
#define IDC_ADAPTIVEDELTA               1157
#define IDC_MAXERROR                    1158
#define IDC_DEFAULTSETTINGS             1159
#define IDC_LOG                         1198

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
